### ISSUE TITLE
Money generation does not work as advertised

### ISSUE THREAD

**Issue by heftymouse** [bvoo/infinitemoney#1]
It generates Money a bunch of times not Infinite Money

Environment:
- Windows 10 Pro x64 19042.928
- Python 3.9.4
- No external dependencies installed

Output:
```
PS C:\Users\Heftymouse\Desktop> python infinitemoney.py
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
Money
...+420
```

Please fix this issue soon, or let me know what I am doing wrong. Thanks!

**Comment by bvoo** [comment]
Hi,

It seems the issue is that you are doing it wrong. Simply generate infinite money instead of endless money.

I'll mark this as closed now. Have a nice day.
